In [124]:
import pandas as pd

_FILE1="../data/Datos PHD.csv"

SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)? (__init__.py, line 51)

In [34]:
file="hello.xlsx"
file[len(file)-5:len(file)]

'.xlsx'

In [41]:
file2 = "hello.xlsx"
file2 = file2[len(file2)-5:len(file2)]
file2

'.xlsx'

In [ ]:
if ".x" in file2:
    print(True)

In [42]:

if ".csv" in file2:
    extension = "csv"
     
    
elif ".xlsx" in file2:
    extension = "xlsx"

extension

'xlsx'

In [46]:
data = pd.read_csv("./data/Datos EPKS raw.csv")
data

,Date,Time,3263_CTR_004AI.daca_ip.pv,3263_CTR_005AI.DACA_IP.PV,3263_CTR_007AI.DACA_IP.PV
0,23-12-22,9:55:00 AM,35.53,23.5,15.3
1,23-12-22,9:54:00 AM,35.57,23.8,15.4
2,23-12-22,9:53:00 AM,36.74,23.5,15.5
3,23-12-22,9:52:00 AM,35.82,24.7,15.4
4,23-12-22,9:51:00 AM,36.36,25.2,15.4
...,...,...,...,...,...
1435,22-12-22,10:00:00 AM,42.51,31.3,15.8
1436,22-12-22,9:59:00 AM,45.01,32.3,16.1
1437,22-12-22,9:58:00 AM,42.25,30.3,16.1
1438,22-12-22,9:57:00 AM,42.72,30.7,16.3
1439,22-12-22,9:56:00 AM,42.08,29.3,16.6

In [120]:
def read_py_systems_excel(filepath):
    try:
        df_data = pd.read_excel(filepath, index_col=2, header=4, parse_dates=True)
        df_data = df_data.drop(df_data.columns[[0, 1, 3]], axis=1) 
        return df_data

    except FileNotFoundError as e:
        print(e)

data= read_py_systems_excel("sample_data.xlsx")
data

                     column_a  column_c  column_d  column_e  column_f
2023-01-01 10:00:00         1         1        10         1        10
2023-01-01 11:00:00         4         2         8         2         8
2023-01-01 12:00:00         9         3         6         3         6
2023-01-01 13:00:00        16         4         4         4         4
2023-01-01 14:00:00        25         5         2         5         2
2023-01-01 15:00:00        29         6         0         6         0
2023-01-01 16:00:00        35         7        -2         7        -2
2023-01-01 17:00:00        41         8        -4         8        -4
2023-01-01 18:00:00        47         9        -6         9        -6
2023-01-01 19:00:00        53        10        -8        10        -8
2023-01-01 20:00:00        59        11       -10        11       -10
2023-01-01 21:00:00        65        12       -12        12       -12
2023-01-01 22:00:00        71        13       -14        13       -14
2023-01-01 23:00:00        77        14       -16        14       -16
2023-01-02 00:00:00        83        15       -18        15       -18

In [135]:
df_data = pd.read_excel("./data/Datos PHD raw.xlsx",index_col=1, header=2, parse_dates=True)
df_data

,Unnamed: 0,PSAG._CV1.READVALUEDCS,PSAG._CV1.LOWLIMIT,PSAG._CV1.HIGHLIMIT,PSAG._CV2.READVALUEDCS,PSAG._CV2.HIGHLIMIT,PSAG._CV2.ACTIVEDELTAHIGHSOFTLIM,PSAG._CV4.READVALUEDCS,PSAG._CV4.HIGHLIMIT,PSAG._CV4.ACTIVEDELTAHIGHSOFTLIM,...,$HSAG.P_INTERMEDIOS_1,$HSAG.P_FINOS_1,PSAG.COMMON.CONTROLLERMODE,$HSAG.SYSSCHED.AX.STF1,$HSAG.SYSSCHED.AX.STF2,$HSAG.SYSSCHED.AX.STF3,$HSAG.SYSSCHED.AX.STF4,$HSAG.SYSSCHED.AX.STF5,$HSAG.SYSSCHED.AX.STF6,PSAG._MV1.READOPVALUE
nan,,,,,,,,,,,,,,,,,,,,,
Timestamp,NaN,PSAG._CV1.READVALUEDCS - Snapshot,PSAG._CV1.LOWLIMIT - Snapshot,PSAG._CV1.HIGHLIMIT - Snapshot,PSAG._CV2.READVALUEDCS - Snapshot,PSAG._CV2.HIGHLIMIT - Snapshot,PSAG._CV2.ACTIVEDELTAHIGHSOFTLIM - Snapshot,PSAG._CV4.READVALUEDCS - Snapshot,PSAG._CV4.HIGHLIMIT - Snapshot,PSAG._CV4.ACTIVEDELTAHIGHSOFTLIM - Snapshot,...,$HSAG.P_INTERMEDIOS_1 - Snapshot,$HSAG.P_FINOS_1 - Snapshot,PSAG.COMMON.CONTROLLERMODE - Snapshot,$HSAG.SYSSCHED.AX.STF1 - Snapshot,$HSAG.SYSSCHED.AX.STF2 - Snapshot,$HSAG.SYSSCHED.AX.STF3 - Snapshot,$HSAG.SYSSCHED.AX.STF4 - Snapshot,$HSAG.SYSSCHED.AX.STF5 - Snapshot,$HSAG.SYSSCHED.AX.STF6 - Snapshot,PSAG._MV1.READOPVALUE - Snapshot
2023-01-31 00:00:00,NaN,5433.992188,5350,5500,7640,12000,11800,1535.14917,2130,2110,...,20.413788,68.092598,1,1,1,0,1,1,0,84.418526
2023-01-31 00:00:15,NaN,5433.757812,5350,5500,7640,12000,11800,1533.384277,2130,2110,...,15.222229,79.132553,1,1,1,0,1,1,0,84.782326
2023-01-31 00:00:30,NaN,5434.467285,5350,5500,7720,12000,11800,1537.622925,2130,2110,...,17.929794,74.632332,1,1,1,0,1,1,0,85.414589
2023-01-31 00:00:45,NaN,5436.724609,5350,5500,7780,12000,11800,1547.135864,2130,2110,...,19.94088,64.992958,1,1,1,0,1,1,0,86.434334
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-01-31 18:59:00,NaN,5300.139648,5250,5400,9870,12000,11800,1747.592407,2130,2110,...,22.808052,64.452316,1,0,1,1,1,0,0,95.786491
2023-01-31 18:59:15,NaN,5300.125,5250,5400,9960,12000,11800,1746.44751,2130,2110,...,20.331879,66.788322,1,0,1,1,1,0,0,95.786491
2023-01-31 18:59:30,NaN,5300.644043,5250,5400,9920,12000,11800,1752.445557,2130,2110,...,24.444992,50.005127,1,0,1,1,1,0,0,95.665375
2023-01-31 18:59:45,NaN,5301.15918,5250,5400,9940,12000,11800,1751.698608,2130,2110,...,20.713226,62.795631,1,0,1,1,1,0,0,95.423203
2023-01-31 19:00:00,NaN,5301.155273,5250,5400,9940,12000,11800,1747.048462,2130,2110,...,29.082787,55.506134,1,0,1,1,1,0,0,95.423203

In [142]:
df_data = pd.read_excel("./data/Datos PHD raw.xlsx",index_col=1, header=2, parse_dates=True)

df_data.iloc[0].name
df_data = df_data.drop(df_data.iloc[0].name)
df_data

,Unnamed: 0,PSAG._CV1.READVALUEDCS,PSAG._CV1.LOWLIMIT,PSAG._CV1.HIGHLIMIT,PSAG._CV2.READVALUEDCS,PSAG._CV2.HIGHLIMIT,PSAG._CV2.ACTIVEDELTAHIGHSOFTLIM,PSAG._CV4.READVALUEDCS,PSAG._CV4.HIGHLIMIT,PSAG._CV4.ACTIVEDELTAHIGHSOFTLIM,...,$HSAG.P_INTERMEDIOS_1,$HSAG.P_FINOS_1,PSAG.COMMON.CONTROLLERMODE,$HSAG.SYSSCHED.AX.STF1,$HSAG.SYSSCHED.AX.STF2,$HSAG.SYSSCHED.AX.STF3,$HSAG.SYSSCHED.AX.STF4,$HSAG.SYSSCHED.AX.STF5,$HSAG.SYSSCHED.AX.STF6,PSAG._MV1.READOPVALUE
nan,,,,,,,,,,,,,,,,,,,,,
2023-01-31 00:00:00,NaN,5433.992188,5350,5500,7640,12000,11800,1535.14917,2130,2110,...,20.413788,68.092598,1,1,1,0,1,1,0,84.418526
2023-01-31 00:00:15,NaN,5433.757812,5350,5500,7640,12000,11800,1533.384277,2130,2110,...,15.222229,79.132553,1,1,1,0,1,1,0,84.782326
2023-01-31 00:00:30,NaN,5434.467285,5350,5500,7720,12000,11800,1537.622925,2130,2110,...,17.929794,74.632332,1,1,1,0,1,1,0,85.414589
2023-01-31 00:00:45,NaN,5436.724609,5350,5500,7780,12000,11800,1547.135864,2130,2110,...,19.94088,64.992958,1,1,1,0,1,1,0,86.434334
2023-01-31 00:01:00,NaN,5437.135254,5350,5500,7840,12000,11800,1551.678589,2130,2110,...,24.571831,62.217987,1,1,1,0,1,1,0,87.694191
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-01-31 18:59:00,NaN,5300.139648,5250,5400,9870,12000,11800,1747.592407,2130,2110,...,22.808052,64.452316,1,0,1,1,1,0,0,95.786491
2023-01-31 18:59:15,NaN,5300.125,5250,5400,9960,12000,11800,1746.44751,2130,2110,...,20.331879,66.788322,1,0,1,1,1,0,0,95.786491
2023-01-31 18:59:30,NaN,5300.644043,5250,5400,9920,12000,11800,1752.445557,2130,2110,...,24.444992,50.005127,1,0,1,1,1,0,0,95.665375
2023-01-31 18:59:45,NaN,5301.15918,5250,5400,9940,12000,11800,1751.698608,2130,2110,...,20.713226,62.795631,1,0,1,1,1,0,0,95.423203
2023-01-31 19:00:00,NaN,5301.155273,5250,5400,9940,12000,11800,1747.048462,2130,2110,...,29.082787,55.506134,1,0,1,1,1,0,0,95.423203

In [ ]:
df

In [104]:
data.dtypes

Unnamed: 0           float64
Unnamed: 2    datetime64[ns]
column_a               int64
column_b               int64
column_c               int64
column_d               int64
column_e               int64
column_f               int64
dtype: object